// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsqQ7f8Qj_YcFZpaIDLrOk9sbhgjqXhO0',
    appId: '1:834815629768:web:5996be01168184305608fd',
    messagingSenderId: '834815629768',
    projectId: 'clear-view-2ec24',
    authDomain: 'clear-view-2ec24.firebaseapp.com',
    storageBucket: 'clear-view-2ec24.firebasestorage.app',
    measurementId: 'G-S1TL1WQ3N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Z8PM_c2Pk4gMlm7Aawlk6EoXxeDB5Mw',
    appId: '1:834815629768:android:23c9dfb76d82a5335608fd',
    messagingSenderId: '834815629768',
    projectId: 'clear-view-2ec24',
    storageBucket: 'clear-view-2ec24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA-EE7tvKrABAhD6MvCzRrvmEct4a3OtI',
    appId: '1:834815629768:ios:0b4a33b5723f63de5608fd',
    messagingSenderId: '834815629768',
    projectId: 'clear-view-2ec24',
    storageBucket: 'clear-view-2ec24.firebasestorage.app',
    iosBundleId: 'com.example.clearView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsqQ7f8Qj_YcFZpaIDLrOk9sbhgjqXhO0',
    appId: '1:834815629768:web:944875c0848d9b585608fd',
    messagingSenderId: '834815629768',
    projectId: 'clear-view-2ec24',
    authDomain: 'clear-view-2ec24.firebaseapp.com',
    storageBucket: 'clear-view-2ec24.firebasestorage.app',
    measurementId: 'G-0Y55R3F27S',
  );
}
